### PR TITLE
fix #254: configure capture device before starting capture session

### LINKED ISSUE #254: bug: unreliable preview view on scan start
### Plugin(s)

- [x] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Version

7.1.0

### Platform(s)

- [ ] Android
- [x] iOS
- [ ] Web

### Current behavior

Starting scans on iOS is not reliable after updating to 7.1.0 from 7.0.0.

I was able to reproduce this with the example barcode-scanning app from `capacitor-mlkit-plugin-demo@30be27c85667e90496551c5a6192b37f2f2353b9` running on an iPhone 16 Pro on iOS 18.3.1.

Using 7.0.0, I am able to open/close the camera repeatedly and reliably get a preview window.

If I upgrade just `@capacitor-mlkit/barcode-scanning` to 7.1.0, opening and closing repeatedly occasionally results in a black screen (but the scanner _is_ still running, but just a black screen is shown curiously!)

### Expected behavior

Camera reliably starts with preview visible.

### Reproduction

https://github.com/robingenz/capacitor-mlkit-plugin-demo/compare/main...ewdurbin:capacitor-mlkit-plugin-demo:reproduce_ios_start_scan_flakiness

### Steps to reproduce

1. Build and run under iOS
2. Open "Barcode Scanning"
3. Press "Start Scan"
4. Dismiss the modal with the "X" button top-right
5. repeat 3-4 until black screen is shown
6. place a barcode in view, note that it still scans

### Other information

_No response_

### Capacitor doctor

$ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 7.0.1
  @capacitor/core: 7.0.1
  @capacitor/android: 7.0.1
  @capacitor/ios: 7.0.1

Installed Dependencies:

  @capacitor/cli: 7.0.0
  @capacitor/core: 7.0.0
  @capacitor/android: 7.0.0
  @capacitor/ios: 7.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [x] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [x] I have attached links to possibly related issues and discussions.
- [x] I understand that incomplete issues (e.g. without reproduction) are closed.

### PR DESCRIPTION
**Pull request by ewdurbin**
This resolves an intermittent issue with the preview screen displaying as black.

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The changes have been tested successfully.
- [x] A changeset has been created (`npm run changeset`).
- [x] I have read and followed the [pull request guidelines](https://capawesome.io/contributing/pull-requests/).

Close #254

### CODE REVIEW

**Comment by robingenz** [comment]
I could not reproduce #254 (i tried it with iPhone 16 Pro). Your fix doesn't break anything for me but I would like to understand what exactly the problem was so we can document it. How did you come up with the fix?

**Comment by ewdurbin** [comment]
This was the thing that set me in the right direction.

https://stackoverflow.com/a/66226157

File: packages/barcode-scanning/ios/Plugin/BarcodeScannerView.swift [hunk 1]
```diff
@@ -83,6 +83,7 @@ public protocol BarcodeScannerViewDelegate {
                 } else {
                     throw RuntimeError(implementation.plugin.errorCannotAddCaptureOutput)
                 }
+                self.configureCaptureDevice(captureDevice)
```
Comment (robingenz) [inline packages/barcode-scanning/ios/Plugin/BarcodeScannerView.swift:86]:
```suggestion
                // Configure capture device to set the correct focus mode and exposure mode.
                // This must be called before commiting the configuration to the capture session
                // and after adding the device input to the capture session.
                self.configureCaptureDevice(captureDevice)
```

File: .changeset/shy-humans-camp.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@capacitor-mlkit/barcode-scanning': patch
+---
+
+barcode-scanning: Resolve intermittent issue with preview display on iOS
```
Comment (robingenz) [inline .changeset/shy-humans-camp.md:5]:
```suggestion
fix(barcode-scanning): opening and closing repeatedly occasionally results in a black screen
```

**Review by robingenz — CHANGES_REQUESTED** [review]

**Review by robingenz — APPROVED** [review]
Thank you!
